sudo:          false
language:      node_js
node_js:
  - 10
install:
  - npm install
script:
  - gulp
cache:
  directories:
    - node_modules

before_deploy:
    - sed -i '/# Build files/q;p' .gitignore
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVIS_TOKEN
  keep_history: false
  on:
    branch: master
